### ISSUE TITLE
关于运行环境配置

### ISSUE THREAD

**Issue by xulu199705** [onion-rain/uestc_health_report#2]
第一次使用时因为没有安装firefox，程序报错了；之后安装firefox之后就可以成功打卡了。
那这就有个问题出现了：必须依赖浏览器的话，是不是没办法在服务器上挂着？
（服务器性能比较弱，担心把其它进程卡住

**Comment by onion-rain** [comment]
![image](https://user-images.githubusercontent.com/40513765/109596471-4d09fe00-7b51-11eb-863b-4aaeb058ad8d.png)

我挂在这上面，性能够用
这脚本资源占用不大的

**Comment by xulu199705** [comment]
soga
我上午的时候把环境在我的服务器上搭好了，成功运行，见下图![image](https://user-images.githubusercontent.com/17242727/109596885-12549580-7b52-11eb-90d3-0496f9cf18bc.png)

另外，在centos上安装依赖库的时候没法安装pywin32，但不影响运行。

另另外，top指令里找不到打卡的进程，所以如果要结束进程该怎么办？

**Comment by onion-rain** [comment]
我没在linux下测试过hhhwindows下直接关闭终端就结束了
![image](https://user-images.githubusercontent.com/40513765/109598752-e1299480-7b54-11eb-9e77-419880984a54.png)
百度得到的答案，你可以试一下

**Comment by xulu199705** [comment]
用schedular.remove还是需要外部给一个输入才行。根本上解决需要创建新进程，再写一个proc_remove.py
目前我想到比较简单的是：
1. 利用宝塔面板的计划任务  
运行run.sh：python3 main.py
2. 利用screen子界面来实现终端不暂停

我这几天试试这两种。

**Comment by onion-rain** [comment]
奥你是远程到服务器，怕关闭远程的时候脚本无法继续执行嘛？
linux下我用tmux
代码里创建进程也可以的

**Comment by xulu199705** [comment]
刚刚查了[介绍](http://www.ruanyifeng.com/blog/2019/10/tmux.html)，应该是这个没错了。  
这几天我还是先把计划注释掉单次运行吧

**Comment by onion-rain** [comment]
https://blog.csdn.net/onion_rain/article/details/104278697
这是我的tmux配置以及常用操作hhh

**Comment by xulu199705** [comment]
收下了，谢谢大犇  
晚上尝试用一下
