### ISSUE TITLE
Windows下无法关闭geckodriver.log

### ISSUE THREAD

**Issue by tinchee** [onion-rain/uestc_health_report#3]
在Windows下运行脚本的时，程序结束似乎无法关闭geckodriver.log，一直存在进程占用该文件，是否有必要使用DriverService来关闭driver？

**Comment by onion-rain** [comment]
试了一下确实是这样，可能需要任务管理器结束firefox进程来解除占用。百度了一下似乎可以增加参数不记录log，有需要可以自行修改一下23333

按道理driver.quit()已经退出了，不知道为啥火狐的进程没有完全退出

**Comment by tinchee** [comment]
貌似可以使用Webdriver下的一个Service函数对driver进行控制
```
 driver_service=Service(webdriver_path)
 driver_service.start()

 driver = webdriver.Firefox(executable_path=webdriver_path, options=options)
 Cookies = driver.get_cookies()
 driver.quit()

 driver_service.stop()
```

**Comment by onion-rain** [comment]
你试了可行嘛？

**Comment by tinchee** [comment]
是的，可行
`from selenium.webdriver.firefox.service import Service`
