### ISSUE TITLE
is:issue is:open 程序第一次运行的时候，是不是首先要将别人的打卡信息存储下来？我试过几次，别人当日没有打卡的，这个程序运行会显示failed！另外login_data是不是只要其中一个人的信息门户账号即可？ 

### ISSUE THREAD

**Issue by SkyZhangEOT** [onion-rain/uestc_health_report#4]
is:issue is:open 程序第一次运行的时候，是不是首先要将别人的打卡信息存储下来？我试过几次，别人当日没有打卡的，这个程序运行会显示failed！另外login_data是不是只要其中一个人的信息门户账号即可？

**Comment by onion-rain** [comment]
emmm，前几天开始不能用一个人的账号给所有人打卡了，现在恐怕需要每个打卡人的信息门户账号才行
