### ISSUE TITLE
帮别人打卡这个bug似乎呗官方修复了

### ISSUE THREAD

**Issue by PrimoWW** [onion-rain/uestc_health_report#5]
嘿 bro thanks for your great job!
最近帮别人打卡这个bug似乎呗官方修复了，我本来一直是用我的账号帮助实验室其他人一起打卡的，然而从昨天开始只能我自己打卡成功了，其他人打卡失败。
你有什么好的idea吗？我想我们可以修复这个bug

**Comment by onion-rain** [comment]
可能需要用每个人的登录信息登录然后打自己的卡了2333
